from turtle import Turtle
import random
color = [
    "Alice Blue",
    "Antique White",
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "Blanched Almond",
    "Blue",
    "Blue Violet",
    "Brown",
    "Burlywood",
    "Cadet Blue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "Cornflower Blue",
    "Cornsilk",
    "Crimson",
    "Cyan",
    "Dark Blue",
    "Dark Cyan",
    "Dark Goldenrod",
    "Dark Gray",
    "Dark Green",
    "Dark Khaki",
    "Dark Magenta",
    "Dark Olive Green",
    "Dark Orange",
    "Dark Orchid",
    "Dark Red",
    "Dark Salmon",
    "Dark Sea Green",
    "Dark Slate Blue",
    "Dark Slate Gray",
    "Dark Turquoise",
    "Dark Violet",
    "Deep Pink",
    "Deep Sky Blue",
    "Dim Gray",
    "Dodger Blue",
    "Firebrick",
    "Floral White",
    "Forest Green",
    "Fuchsia",
    "Gainsboro",
    "Ghost White",
    "Gold",
    "Goldenrod",
    "Gray",
    "Web Gray",
    "Green",
    "Web Green",
    "Green Yellow",
    "Honeydew",
    "Hot Pink",
    "Indian Red",
    "Indigo",
    "Ivory",
    "Khaki",
    "Lavender",
    "Lavender Blush",
    "Lawn Green",
    "Lemon Chiffon",
    "Light Blue",
    "Light Coral",
    "Light Cyan",
    "Light Goldenrod",
    "Light Gray",
    "Light Green",
    "Light Pink",
    "Light Salmon",
    "Light Sea Green",
    "Light Sky Blue",
    "Light Slate Gray",
    "Light Steel Blue",
    "Light Yellow",
    "Lime",
    "Lime Green",
    "Linen",
    "Magenta",
    "Maroon",
    "Web Maroon",
    "Medium Aquamarine",
    "Medium Blue",
    "Medium Orchid",
    "Medium Purple",
    "Medium Sea Green",
    "Medium Slate Blue",
    "Medium Spring Green",
    "Medium Turquoise",
    "Medium Violet Red",
    "Midnight Blue",
    "Mint Cream",
    "Misty Rose",
    "Moccasin",
    "Navajo White",
    "Navy Blue",
    "Old Lace",
    "Olive",
    "Olive Drab",
    "Orange",
    "Orange Red",
    "Orchid",
    "Pale Goldenrod",
    "Pale Green",
    "Pale Turquoise",
    "Pale Violet Red",
    "Papaya Whip",
    "Peach Puff",
    "Peru",
    "Pink",
    "Plum",
    "Powder Blue",
    "Purple",
    "Web Purple",
    "Rebecca Purple",
    "Red",
    "Rosy Brown",
    "Royal Blue",
    "Saddle Brown",
    "Salmon",
    "Sandy Brown",
    "Sea Green",
    "Seashell",
    "Sienna",
    "Silver",
    "Sky Blue",
    "Slate Blue",
    "Slate Gray",
    "Snow",
    "Spring Green",
    "Steel Blue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Violet",
    "Wheat",
    "White",
    "White Smoke",
    "Yellow",
    "Yellow Green",
]
rand_color = random.choice(color)
class Food(Turtle):
    def __init__(self):
        super().__init__()
        self.shape("turtle")
        self.penup()
        self.shapesize(stretch_len=.5, stretch_wid=.5)
        self.speed("fastest")
        self.refresh()
        

    def refresh(self):
        self.goto(x=random.randint(-250, 250), y=random.randint(-250, 250))
        self.color(rand_color)
        
# A food appears somewhere random on the screen
# When the head of the snake touches the food
# add a segment to the snake
# Food appears somewhere else that's random.
# If snake hits itself gameover
# If snake hits wall. Gameover
